"""web test

Revision ID: 1081d3b00eb
Revises: 38c79365869e
Create Date: 2016-04-22 21:21:43.132513

"""

# revision identifiers, used by Alembic.
revision = '1081d3b00eb'
down_revision = '38c79365869e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
